#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function install
{
    PACKAGES="$1"

    if [ "$PKG_MANAGER" == "apt" ];
    then
        echo "Installing packages '$PACKAGES' ..."
        echo "-----------------------------------"
        sudo apt install -y $PACKAGES
    else
        abort "Unknown package manager '${$PKG_MANAGER}'."
        abort "Installation failed. "
    fi

    if ! [ "$?" == "0" ];
    then
        abort "Installation failed."
    fi
}




NEEDED_PACKAGES=""
WINE_SETUP_REPO="https://github.com/arithesage/termux-setup.git"

cat /etc/os-release | grep debian > /dev/null

if [ "$?" == "0" ];
then
    export PKG_MANAGER="apt"
fi


if ! [ "$TERMUX_VERSION" == "" ];
then
    if ! [ -f "$PREFIX/bin/git" ];
    then
        NEEDED_PACKAGES+="git"
    fi

elif ! [ -f "/usr/bin/git" ];
    NEEDED_PACKAGES+="git"
fi


if ! [ "$NEEDED_PACKAGES" == "" ];
then
    install "$NEEDED_PACKAGES"
fi


git clone $WINE_SETUP_REPO $HOME/github/wine-setup --depth=1

